<div data-bind="scope: 'randomReview'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "randomReview": {
                    "component": "Training_Task44/js/review",
                    "config": {
                        "template": "Training_Task44/review",
                        "url": <?= json_encode($block->getUrl('training_task44/index/index')) ?>
                    }
                }
            }
        }
    }
}
</script>